### ISSUE TITLE
Missing functions in the C file

### ISSUE THREAD

**Issue by MyVanitar** [STMicroelectronics/ili9325#1]
Hi,
it looks like there is no implementation of these functions in the C file

```c
 void  LCD_IO_WriteMultipleData(uint8_t *pData, uint32_t Size);
 void  LCD_IO_WriteReg(uint8_t Reg);
 ```

**Comment by RKOUSTM** [comment]
Hi @MyVanitar,

Thank you for your report. The ili9325 BSP LCD component is supported by the following STM32 boards: 
- STM3210C_EVAL
- STM322xG_EVAL
- STM324xG_EVAL
- STM32446E_EVAL
- STM32L152D_EVAL

In fact, the LCD_IO_WriteReg() and the LCD_IO_WriteMultipleData() function are implemented in the C file of each BSP driver board as the [stm32446e_eval.c](https://github.com/STMicroelectronics/stm32446e-eval/blob/75745e5711c955957f55db224ac7afb577cfd597/stm32446e_eval.c#L192-L193) file. So, in order to correctly compile your application, you need to include the necessary files of the BSP board used. It is very important that you use a consistent set of CMSIS - HAL - BSP versions, as mentioned in the release note. You can refer to [this](https://github.com/STMicroelectronics/STM32CubeF4/tree/master/Projects/STM32446E_EVAL/Examples/BSP) BSP example on the STM32446E_EVAL to test the different features of the ili9325 LCD driver.

Please allow me to close this issue now. Thank you for your report.

With regards,
